version: '3.8'
services:
  ui:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev"
    
  api:
    image: python:3.10
    working_dir: /app/src/project-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    command: >
      sh -c "pip install -r requirements.txt && python -m app"