version: '3.8'
services:
  ui:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev"

  db:
    image: postgres:16 # Use the official PostgreSQL image
    container_name: postgres-db
    ports:
      - "5432:5432" # Expose the PostgreSQL default port
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    
  api:
    image: python:3.10
    working_dir: /app/src/project-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    command: >
      sh -c "pip install -r requirements.txt && python app.py"